# Created with podman-5.5.2
apiVersion: v1
kind: Pod
metadata:
  annotations:
  labels:
    app: rpmfusion
  name: rpmfusion
spec:
  containers:
  - args:
    - nginx
    - -g
    - daemon off;
    image: localhost/rpmfusion-website:2.0
    name: website
    ports:
    - containerPort: 80
      hostPort: 8055

