ARG NODE_VERSION=20-alpine
FROM node:${NODE_VERSION} AS doc-builder

WORKDIR /app

COPY package.json .
COPY yarn.lock .
RUN yarn install --silent

ENV PATH /app/node_modules/.bin:${PATH}

COPY . .

RUN yarn build

# Runtime image
FROM nginx:1.29.0-alpine AS website

LABEL vendor="RPM Fusion" \
      org.rpmfusion.appname="Website" \
      maintainer="RPM Fusion Infrastructure <admin@rpmfusion.org>"

COPY --from=doc-builder /app/build /usr/share/nginx/html
COPY deployment/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
